version: '2'
services:
  #database : mongo db
  mongo:
    image: mongo:latest
    volumes:
    - /opt/mongodb/db:/data/db
    restart: never
  #rest api engie : node + code
  api:
    depends_on:
    - mongo
    image: node:alpine
    volumes:
    - ./eps-shared-api/:/usr/src/app
    links:
    - mongo
    ports: 
    - "8080:8080"
    restart: never
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm start'
  web:
    image: node:alpine
    ports:
    - 4200:4200
    restart: never
    working_dir: /usr/src/app
    volumes:
    - "./eps-shared-web/:/usr/src/app"
    command: sh -c 'npm install; npm start'
