version: '2'
services:
  #database : mongo db
  mongo:
    image: mongo:latest
    volumes:
    - /opt/mongodb/db:/data/db
    restart: always
  #rest api engie : node + code
  load-balancer-api:
    ports:
    - ${HOST_PORT_API}
    image: rancher/lb-service-haproxy:v0.4.6
    labels:
      proxy_url: ${EXPOSE_API_URL}
  api:
    image: krack/aps-shared-api:${TAG}
    links:
    - mongo
    restart: always
    environment:
    - ALLOW_URL=http://${EXPOSE_SITE_URL}
    - SERVER_HOST=http://${EXPOSE_API_URL}
    - SERVER_PORT=${HOST_PORT_API}
    - SERVER_PUBLIC_PORT=80
    - STORAGE_USERNAME=aRhyvaAcSdDd
    - STORAGE_PASSWORD=cfEADZUdc2NumRatjdTj89yxDf9JYhRd
    - STORAGE_TENANT_ID=38edd2464f9e4bf7b3f7ee79e45b09a7
    - STORAGE_AUTHENTICATION_URL=https://auth.cloud.ovh.net
    - STORAGE_REGION=gra1
    labels:
      io.rancher.container.pull_image: always
  #web site : static with apache
  load-balancer-web:
    ports:
    - ${HOST_PORT_WEB}
    image: rancher/lb-service-haproxy:v0.4.6
    labels:
      proxy_url: ${EXPOSE_SITE_URL}
  web:
    image: httpd:2.4
    image: krack/aps-shared-web:${TAG}
    restart: always
    labels:
      io.rancher.container.pull_image: always
